
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const ERROR = 'APP/ERROR';
export const CLEAR_ERROR = 'APP/CLEAR_ERROR';
export const MESSAGE = 'APP/MESSAGE';
export const CLEAR_MESSAGE = 'APP/CLEAR_MESSAGE';

// AUTH
export const CHANGE_AUTH_FORM = 'AUTH/CHANGE_AUTH_FORM';

// COMPANY
export const ADD_COMPANY = 'COMPANY/CREATE';
export const GET_COMPANIES = 'COMPANY/GET_ALL';
export const CLEAR_COMPANIES = 'COMPANY/CLEAR_ALL';
export const SELECT_COMPANY = 'COMPANY/SELECT';

// CHARTS
export const GET_DAILY_CHART = 'CHART/GET_DAILY_CHART';